"""add password field in Viewer

Revision ID: 3c03ce1a7e0a
Revises: 226d3ea7183d
Create Date: 2023-02-17 19:49:39.068280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c03ce1a7e0a'
down_revision = '226d3ea7183d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewer', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viewer', 'password')
    # ### end Alembic commands ###
